### ISSUE TITLE
App saying there's no bill text when Congress.gov has bill text

### ISSUE THREAD

**Issue by nickom** [sunlightlabs/congress-ios#429]
Could be an issue with the API, but some bills in the app say there's no bill text:
![img_1968](https://cloud.githubusercontent.com/assets/3171982/5927340/da6d62b6-a63f-11e4-814c-153929adcd74.PNG)
But when you click to view the text on Congress.gov, it's there:
![img_1967](https://cloud.githubusercontent.com/assets/3171982/5927350/ef63e618-a63f-11e4-8460-59be549e373c.PNG)
![img_1965](https://cloud.githubusercontent.com/assets/3171982/5927354/f3bb5b10-a63f-11e4-8245-8e80ddaac929.PNG)

**Comment by jcarbaugh** [comment]
API issue.

**Comment by handlers** [comment]
looking into it

**Comment by handlers** [comment]
So we narrowed this down a bit: the issue is that there will be _notifications_ that say there's no bill text, when in reality there is bill text on congress.gov.

**Comment by dcloud** [comment]
Is the bill text issue in the API resolved, @handlers?

**Comment by handlers** [comment]
@dcloud nope. If I remember right, It's not quite an API issue so much as an issue of synchronizing the API and the notifications (notifications may get queued up before the API gets bill text). I think @nickom was going to stay on the lookout for future instances, right? cc @jcarbaugh
